<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Honors\Module'                       => __DIR__ . '/Module.php',
    'Honors\Controller\AuthController'    => __DIR__ . '/src/Honors/Controller/AuthController.php',
    'Honors\Controller\SuccessController' => __DIR__ . '/src/Honors/Controller/SuccessController.php',
    'Honors\Model\MyAuthStorage'          => __DIR__ . '/src/Honors/Model/MyAuthStorage.php',
    'Honors\Model\User'                   => __DIR__ . '/src/Honors/Model/User.php',
);