

<?php
// module/Album/view/album/album/edit.phtml:
use Zend\Form\Element\File;
use Zend\Form\Element\DateTime;
use Zend\Captcha;
use Zend\Form\Element;


// TODO

$title = 'Edit Honors Record';
$this->headTitle($title);
?>

<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>jQuery UI Datepicker - Default functionality</title>
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script> 
  <script src='http://jquery-multifile-plugin.googlecode.com/svn/trunk/jquery.js' type="text/javascript"></script>
  <link type="text/css" href="http://www.fyneworks.com/@/js/jquery/ui/jquery.ui.css" rel="stylesheet"/>
  
  
  <?php 
  echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.MultiFile.js')
 			->prependFile($this->basePath() . '/js/jquery.MetaData.js')  
    		->prependFile($this->basePath() . '/js/jquery.form.js')  
    		->appendFile($this->basePath() . '/js/jquery-ui.min.js') 
  ?>       
  
  <link rel="stylesheet" href="/resources/demos/style.css" />
  <script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
  </script>
</head>
<body>
 

<h1><?php echo $this->escapeHtml($title); ?></h1>


<form name="edit"  method="post"  enctype="multipart/form-data">
<!-- 
<a href="javascript:history.go(-1)"><img src="<?php echo $this->basepath() . '/images/back_blk.jpg'?>" alt="Go Back"/></a> 
-->
<table class="table">



<input type="hidden" name="honors_id" value="<?php echo $this->escapeHtml($data->id);?>">
<tr>
    <td>
        <b>First Name</b>
    </td>

	<td>
        <input type="text" name="firstname" value="<?php echo $this->escapeHtml($data->firstname);?>">
    </td>
</tr>
<tr>
    <td>
        <b>Last Name</b>
    </td>
    
    <td>
        <input type="text" name="lastname" value="<?php echo $this->escapeHtml($data->lastname);?>">
    </td>
               
</tr>

<tr>
    <td>
        <b>State</b>
        <?php echo $this->escapeHtml($data->state);?>
    </td>
    

    <td>
        <select name="states">
        <option value="">Please Choose</option>
          
        <?php               
        foreach($states as $res){                               
           if($data->state == $res['state']){
               echo '<option value="'.$res['state'].'" selected>'.$res['state'].'</option>';
           }
           else{
               echo '<option value="'.$res['state'].'">'.$res['state'].'</option>';
           }
        }
        ?>
        </select>                
    </td>
               
</tr>
    


<tr>
    <td>
        <b>Attachments</b>
    </td>
    
    <td>
        <input type="file" name="fileupload"   >
        
    </td>     
</tr>

<tr>
    <td align="center">
        <input type="submit" name="submit" value="Update">
    </td>
    <td align="center">
        <input type="button" name="Cancel" value="Cancel" onClick="javascript:history.go(-1)">
    </td>     
         
</tr>
<tr>
    <td colspan="2" align="center">

<?php 
$captcha = new Element\Captcha('captcha');
$captcha
->setCaptcha(new Captcha\Dumb())
->setLabel('Please verify you are human');

// Within your view...

echo $this->formCaptcha($captcha);

?>
    </td>     
</tr>

</table>

</form>




</body>

</html>