<?php
// module/Album/view/album/album/index.phtml:

$title = 'Honors Students(Admin Only)';
$this->headTitle($title);
?>


<h1><?php echo $this->escapeHtml($title); ?></h1>

<form name="edit"  method="post"  enctype="multipart/form-data">
<div class="table" align="center">
    Search
    <input type"text" size="40" name="searchStr" value="<?php echo $this->escapeHtml($srchStr); ?>">
    <input type="submit" name="submit" value="Search"><br><br>
    <input type="button" name="add" value="Add a New Student" onClick="location.href='<?php echo $this->url('honors', array('action'=>'add'));?>'">
    <a href="<?php echo $this->url('honors', array('action'=>'add'));?>">Add new album</a>
</div>
</form>
<hr>
<table class="table">

<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Academic Year</th>
    <th>&nbsp;</th>
</tr>

<?php foreach ($data as $item) : ?>

<tr>       
    <td><a href="<?php echo $this->url('honors', array('action'=>'edit','id'=>$item->getId()));?>"><?php echo $this->escapeHtml($item->getFirstname());?></a></td>
	<td><?php echo $this->escapeHtml($item->getLastname());?></td>
    <td><?php echo $this->escapeHtml($item->getAcadyear());?></td>   
    <td>    
       <a href="<?php echo $this->url('honors', array('action'=>'delete','id'=>$item->getId()));?>">Delete </a>    
    </td>
</tr>
<?php endforeach; ?>

</table>
 
 
 

