<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Housing\Module'                       => __DIR__ . '/Module.php',
    'Housing\Controller\AuthController'    => __DIR__ . '/src/Housing/Controller/AuthController.php',
    'Housing\Controller\SuccessController' => __DIR__ . '/src/Housing/Controller/SuccessController.php',
    'Housing\Model\MyAuthStorage'          => __DIR__ . '/src/Housing/Model/MyAuthStorage.php',
    'Housing\Model\User'                   => __DIR__ . '/src/Housing/Model/User.php',
);