<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tranreq\Module'                        => __DIR__ . '/Module.php',
    'Tranreq\Controller\TranreqController' => __DIR__ . '/src/Tranreq/Controller/TranreqController.php',
    'TranreqTest\Framework\TestCase'        => __DIR__ . '/tests/Tranreq/Framework/TestCase.php',
    'TranreqTest\SampleTest'                => __DIR__ . '/tests/Tranreq/SampleTest.php',
);
