

<?php
// module/Album/view/album/album/edit.phtml:
use Zend\Form\Element\File;
use Zend\Form\Element\DateTime;
$title = 'Edit album';
$this->headTitle($title);
?>

<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>jQuery UI Datepicker - Default functionality</title>
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script> 
  <script src='http://jquery-multifile-plugin.googlecode.com/svn/trunk/jquery.js' type="text/javascript"></script>
  <link type="text/css" href="http://www.fyneworks.com/@/js/jquery/ui/jquery.ui.css" rel="stylesheet"/>
  
  <?php 
  echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.MultiFile.js')
 			->prependFile($this->basePath() . '/js/jquery.MetaData.js')  
    		->prependFile($this->basePath() . '/js/jquery.form.js')  
    		->appendFile($this->basePath() . '/js/jquery-ui.min.js') 
  ?>
   
  
  
  
  
  
  <link rel="stylesheet" href="/resources/demos/style.css" />
  <script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
  </script>
</head>
<body>
 

<h1><?php echo $this->escapeHtml($title); ?></h1>

<form name="edit"  method="post"  enctype="multipart/form-data">
<table class="table">



<input type="hidden" name="id" value="<?php echo $this->escapeHtml($album->id);?>">
<tr>
    <td>
        <b>Artist</b>
    </td>

	<td>
        <input type="text" name="artist" value="<?php echo $this->escapeHtml($album->artist);?>">
    </td>
</tr>
<tr>
    <td>
        <b>Title</b>
    </td>
    
    <td>
        <input type="text" name="title" value="<?php echo $this->escapeHtml($album->title);?>">
    </td>
               
</tr>

<tr>
    <td>
        <b>Genre</b>
    </td>
    
    <td>
        <select name="genre">
        <option value="">Please Choose</option>  
        <?php        
        foreach($genre as $gnr){ 
          
           if($album->genre == $gnr->title){
               echo '<option value="'.$gnr->title.'" selected>'.$gnr->title.'</option>';
           }
           else{
               echo '<option value="'.$gnr->title.'">'.$gnr->title.'</option>';
           }
        }
        ?>
        </select>         
        
    </td>
               
</tr>



<tr>
    <td>
        <b>Release Date <?php echo $this->escapeHtml($album->date_release);?></b>
    </td>
    
    <td>    
        <input type="text" id="datepicker" name="date_release" value="<?php echo $this->escapeHtml($album->date_release);?>">
    </td>
               
</tr>


<tr>
    <td>
        <b>Attachments</b>
    </td>
    
    <td>
        <input type="file" name="fileupload"   >
        
    </td>     
</tr>

<!---
<tr>
    <td>
        <b>Release Date</b>
    </td>
    
    <td>    
        <input type="date" name="date_release" value="<?php echo $this->escapeHtml($album->date_release);?>">
    </td>
               
</tr>

--->
<tr>
    <td colspan="2" align="center">
        <input type="submit" name="submit" value="Update">
    </td>     
</tr>

</table>

</form>



</body>

</html>