<div class="hero-unit">
	<h1><?php echo sprintf($this->translate('Plato Application Hub')) ?></h1>
	<p><?php echo sprintf($this->translate('Welcome to Plato - The Math Placement Exam Registration RSVP/Center ')) ?></p>
	<p>
		<a class="btn btn-success btn-large"
			href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a>
	</p>
</div>

<div class="row">

	<div class="span4">
		<h2><?php echo $this->translate('Plato Main Application') ?></h2>
		<p>
		<?php echo sprintf($this->translate('This is the Plato application Please follow the steps')) ?>
		</p>
		<p>
			<a class="btn btn-success" href="main"
				target="_blank"><?php echo $this->translate('Plato') ?> &raquo;</a>
		</p>
	</div>

		<div class="span4">
		<h2><?php echo $this->translate('Plato Admin Application') ?></h2>
		<p>
		<?php echo sprintf($this->translate('This is the Plato admin application Please follow the steps')) ?>
		</p>
		<p>
			<a class="btn btn-success" href="admin"
				target="_blank"><?php echo $this->translate('Plato Admin') ?> &raquo;</a>
		</p>
	</div>

		<div class="span4">
		<h2><?php echo $this->translate('Plato MTC Application') ?></h2>
		<p>
		<?php echo sprintf($this->translate('This is the Plato MTC application Please follow the steps')) ?>
		</p>
		<p>
			<a class="btn btn-success" href="mtc"
				target="_blank"><?php echo $this->translate('Plato MTC') ?> &raquo;</a>
		</p>
	</div>
</div>
