<div id="footer">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span6 pull-right">               
                <ul class="social-grid">
                    <li>
                        <div class="social-item">				
                            <div class="social-info-wrap">
                                <div class="social-info">
                                    <div class="social-info-front social-small-twitter">
                                        <a href="http://twitter.com"></a>
                                    </div>
                                    <div class="social-info-back social-small-twitter-hover">
                                        <a href="http://twitter.com"></a>
                                    </div>	
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="social-item">				
                            <div class="social-info-wrap">
                                <div class="social-info">
                                    <div class="social-info-front social-small-facebook">
                                        <a href="http://facebook.com"></a>
                                    </div>
                                    <div class="social-info-back social-small-facebook-hover">
                                        <a href="http://facebook.com"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="social-item">				
                            <div class="social-info-wrap">
                                <div class="social-info">
                                    <div class="social-info-front social-small-youtube">
                                        <a href="http://dribbble.com"></a>
                                    </div>
                                    <div class="social-info-back social-small-youtube-hover">
                                        <a href="http://dribbble.com"></a>
                                    </div>	
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="social-item">				
                            <div class="social-info-wrap">
                                <div class="social-info">
                                    <div class="social-info-front social-small-rss">
                                        <a href="http://flickr.com"></a>
                                    </div>
                                    <div class="social-info-back social-small-rss-hover">
                                        <a href="http://flickr.com"></a>
                                    </div>	
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>         
            </div>

            <div class="span6 pull-left unlv">
                <h3>University of Nevada, Las Vegas</h3>
            </div>
        </div>
    </div>
</div>