<?php
//determine uri for the nav styling
$url = $this->url();
$segment = explode('/', $url);
$base = $segment[1];
$uri = $segment[2];
//doctype
echo $this->doctype();
?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('Student Enrollment Technology'. $this->translate('Rooster Template'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

        <!-- Le styles -->
        <?php

								echo $this->headLink ( array (
										'rel' => 'shortcut icon',
										'type' => 'image/vnd.microsoft.icon',
										'href' => $this->basePath () . '/images/favicon.ico'
								) )->prependStylesheet ( $this->basePath () . '/css/bootstrap-responsive.min.css' )->prependStylesheet ( $this->basePath () . '/css/style.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap.min.css' )?>

        <!-- Scripts -->
        <?php

								echo $this->headScript ()->prependFile ( $this->basePath () . '/js/html5.js', 'text/javascript', array (
										'conditional' => 'lt IE 9'
								) )->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )->prependFile ( $this->basePath () . '/js/jquery.min.js' )?>

</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a>
				<a class="brand" href="http://www.unlv.edu"><img alt="" src=""><!-- <span class="icon-bar">--></span><span class="icon-bar"></span><span class="icon-bar"></span></a>

				<div class="nav-collapse collapse">
					<ul class="nav">
						<li class="<?=($uri == "app" ? 'active' : 'navbar-link')?>">
							<a href="<?php echo $this->url('template') ?>">
								<?php echo $this->translate('Template') ?>
							</a>
						</li>

						<li class="<?=($uri == "" ? 'active' : 'navbar-link')?>">
							<a href="<?php echo $this->url('home') ?>">
								<?php echo $this->translate('Home') ?>
							</a>
						</li>

						<li class="<?=($uri == 'plato' ? 'active': 'navbar-link')?>">
							<a href="<?php echo $this->url('plato') ?>">
								<?php echo $this->translate('Plato') ?>
							</a>
						</li>

						<li class="<?=($uri == 'tranreq' ? 'active' : 'navbar-link')?>">
							<a href="<?php echo $this->url('tranreq') ?>">
								<?php echo $this->translate('Transcript Request') ?>
							</a>
						</li>
					</ul>
				</div>
				<!--/.nav-collapse -->

			</div>
		</div>
	</div>

	<div class="container">
		<h3>Student Enrollment Technology</h3>
		<?php echo $this->content; ?>
		<hr>
		<footer>
			<?php include('footernavigation.phtml')?>
	</footer>
	</div>

	<!-- /container -->
        <?php echo $this->inlineScript()?>
</body>
</html>