
<div class="hero-unit">
    <h1><?php echo sprintf($this->translate($this->title)) ?></h1>
    <p><?php echo sprintf($this->translate($this->content)) ?></p>
    <!--<p><? //print_r($this->uri);    ?></p>-->

    <div class="container-fluid">        
        
<!--        <div class="well span4 feature">
            <h2><?= $this->translate($this->option1) ?></h2>
            <p>You have a student ID?</p>
            <a class="btn btn-success btn-large" href="current" target="_self"><?php echo $this->translate($this->option1) ?> &raquo;</a>
        </div>
        
        <div class="well span4 feature">
            <h2><?= $this->translate($this->option2) ?></h2>
            <p>Don't have a student ID</p>
            <a class="btn btn-success btn-large" href="future" target="_self"><?php echo $this->translate($this->option2) ?> &raquo;</a>
        </div>-->
    
    </div>
</div>