<strong>Module:</strong>        Album &raquo;
<strong>Controller:</strong>    Album &raquo;
<strong>Action:</strong>        foo


<form name="upload-form" id="upload-form" method="post" enctype="multipart/form-data">
    <div class="form-element">
        <label for="image-file">Avatar Image Upload</label>
        <input type="file" name="image-file" id="image-file">
    </div>

    <button>Submit</button>
</form>
